# Generated by Django 5.1.3 on 2026-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberregistration',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='polling_station',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='role_interest',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='skills',
        ),
        migrations.AlterField(
            model_name='memberregistration',
            name='age_bracket',
            field=models.CharField(choices=[], max_length=10),
        ),
    ]
