# Generated by Django 5.1.3 on 2026-05-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_memberregistration_id_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberregistration',
            old_name='sub_county',
            new_name='constituency',
        ),
        migrations.RemoveField(
            model_name='memberregistration',
            name='age_bracket',
        ),
    ]
